package form.util;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("LogFormatter Utility Tests")
class LogFormatterTest {

    @Test
    @DisplayName("Should escape CSV text containing comma")
    void shouldEscapeCSVTextContainingComma() {
        String text = "Choice A, Choice B";
        String escaped = LogFormatter.escapeCSV(text);

        assertEquals("\"Choice A, Choice B\"", escaped);
    }

    @Test
    @DisplayName("Should escape CSV text containing double quote")
    void shouldEscapeCSVTextContainingDoubleQuote() {
        String text = "He said \"Hello\"";
        String escaped = LogFormatter.escapeCSV(text);

        assertEquals("\"He said \"\"Hello\"\"\"", escaped);
    }

    @Test
    @DisplayName("Should escape CSV text containing newline")
    void shouldEscapeCSVTextContainingNewline() {
        String text = "Line 1\nLine 2";
        String escaped = LogFormatter.escapeCSV(text);

        assertEquals("\"Line 1\nLine 2\"", escaped);
    }

    @Test
    @DisplayName("Should not escape CSV text without special characters")
    void shouldNotEscapeCSVTextWithoutSpecialCharacters() {
        String text = "Simple text";
        String escaped = LogFormatter.escapeCSV(text);

        assertEquals("Simple text", escaped);
    }

    @Test
    @DisplayName("Should return empty string when escaping null")
    void shouldReturnEmptyStringWhenEscapingNull() {
        String escaped = LogFormatter.escapeCSV(null);

        assertEquals("", escaped);
    }

    @Test
    @DisplayName("Should escape CSV text with multiple special characters")
    void shouldEscapeCSVTextWithMultipleSpecialCharacters() {
        String text = "Text with, comma and \"quotes\" and\nnewline";
        String escaped = LogFormatter.escapeCSV(text);

        assertEquals("\"Text with, comma and \"\"quotes\"\" and\nnewline\"", escaped);
    }

    @Test
    @DisplayName("Should get timestamp in correct format")
    void shouldGetTimestampInCorrectFormat() {
        String timestamp = LogFormatter.getTimestamp();

        // Verify format: yyyy-MM-dd HH:mm:ss.SSS
        assertNotNull(timestamp);
        assertTrue(timestamp.matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3}"));
    }

    @Test
    @DisplayName("Should create log entry with provided timestamp")
    void shouldCreateLogEntryWithProvidedTimestamp() {
        String timestamp = "2025-12-15 10:30:00.123";
        String actionType = "CHOICE_SELECTED";
        String details = "Choice A";

        String logEntry = LogFormatter.createLogEntry(timestamp, actionType, details);

        assertEquals("2025-12-15 10:30:00.123,CHOICE_SELECTED,Choice A", logEntry);
    }

    @Test
    @DisplayName("Should create log entry with provided timestamp and escape details")
    void shouldCreateLogEntryWithProvidedTimestampAndEscapeDetails() {
        String timestamp = "2025-12-15 10:30:00.123";
        String actionType = "REASON_INPUT";
        String details = "I chose this, because it's good";

        String logEntry = LogFormatter.createLogEntry(timestamp, actionType, details);

        assertEquals("2025-12-15 10:30:00.123,REASON_INPUT,\"I chose this, because it's good\"", logEntry);
    }

    @Test
    @DisplayName("Should create log entry with auto-generated timestamp")
    void shouldCreateLogEntryWithAutoGeneratedTimestamp() {
        String actionType = "QUESTION_DISPLAYED";
        String details = "Question 1";

        String logEntry = LogFormatter.createLogEntry(actionType, details);

        // Verify format
        assertTrue(logEntry.matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3},QUESTION_DISPLAYED,Question 1"));
    }

    @Test
    @DisplayName("Should create log entry with auto-generated timestamp and escape details")
    void shouldCreateLogEntryWithAutoGeneratedTimestampAndEscapeDetails() {
        String actionType = "CHOICE_SELECTED";
        String details = "Choice A, Choice B";

        String logEntry = LogFormatter.createLogEntry(actionType, details);

        // Verify format and CSV escaping
        assertTrue(logEntry.matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3},CHOICE_SELECTED,\"Choice A, Choice B\""));
    }

    @Test
    @DisplayName("Should format question number correctly")
    void shouldFormatQuestionNumberCorrectly() {
        assertEquals("Q1", LogFormatter.formatQuestionNumber(1));
        assertEquals("Q5", LogFormatter.formatQuestionNumber(5));
        assertEquals("Q100", LogFormatter.formatQuestionNumber(100));
    }

    @Test
    @DisplayName("Should format question number zero")
    void shouldFormatQuestionNumberZero() {
        assertEquals("Q0", LogFormatter.formatQuestionNumber(0));
    }

    @Test
    @DisplayName("Should format negative question number")
    void shouldFormatNegativeQuestionNumber() {
        assertEquals("Q-1", LogFormatter.formatQuestionNumber(-1));
    }
}
